/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarCard: typeof import('./src/components/CalendarCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProgressOverviewCard: typeof import('./src/components/ProgressOverviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskContainer: typeof import('./src/components/TaskContainer.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
  }
}
